from pdf2image import convert_from_path
from PIL import Image

# Step 1: Convert PDF pages to images
pdf_path = 'git and github.pdf'  # Your input PDF file
images = convert_from_path(pdf_path)

# Step 2: Combine the images vertically
widths, heights = zip(*(i.size for i in images))
total_height = sum(heights)
max_width = max(widths)

# Create a blank image with the combined height of all pages
merged_image = Image.new('RGB', (max_width, total_height))

y_offset = 0
for img in images:
    merged_image.paste(img, (0, y_offset))
    y_offset += img.size[1]

# Step 3: Save the merged image
merged_image_path = 'merged_image.png'
merged_image.save(merged_image_path)

# Step 4: Create an HTML file and embed the image with CSS for beautiful colors
output_html = "output.html"
html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Merged PDF as Image</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f0f8ff; /* Light blue background */
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            color: #333;
        }}
        .container {{
            text-align: center;
            padding: 20px;
            background-color: #fff; /* White background for the content */
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Subtle shadow */
        }}
        h1 {{
            color: #2c3e50; /* Dark blue for the heading */
        }}
        img {{
            max-width: 90%;
            height: auto;
            border: 5px solid #3498db; /* Light blue border around the image */
            border-radius: 10px;
            margin-top: 20px;
        }}
        footer {{
            margin-top: 20px;
            font-size: 14px;
            color: #777;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Merged PDF Content</h1>
        <img src="{merged_image_path}" alt="Merged PDF Image">
        <footer>Generated by Python Script</footer>
    </div>
</body>
</html>
"""

# Write the HTML content to a file
with open(output_html, 'w') as f:
    f.write(html_content)

print(f"HTML file with beautiful colors has been created: {output_html}")
